### ISSUE TITLE
Database.yml is hardpointing to the env-vars set by docker-compose.

### ISSUE THREAD

**Issue by vjustov** [ruby-do/RSVP#2]
I'm just checking this and I notice that the database yaml is hardpointing to the env-vars set by docker-compose, forcing me to use docker to run the app. I believe this is not the intended behavior. In the cases where you are using ruby and NOT docker you'd have to install docker and familiarize yourself at least a tiny bit with it, because its a new dependency that encapsulates your whole app.

I think having the possibility of starting the app normally AND with docker should be the aim. thoughts?
This should be, in theory, just changing the database.yml to point to some env-var like DB_HOSTNAME, DB_PORT, etc and make the rsvpdb container expose those variables.

**Comment by gotjosh** [comment]
I like this idea, I too think we should allow the user to choose whenever they want to dockerize or not so anything that gives us more flexibility is a :+1: 

You can specify via the compose file which variables and what name they map to.

**Comment by jlbenc** [comment]
Also, could use dotenv to set the default dev/test creds:

gem 'dotenv-rails', :groups => [:development, :test]
